files:
  - source: /*.md
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%.%file_extension%
  - source: /*/*.md
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%.%file_extension%
  - source: /*/*/*.md
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%.%file_extension%
